import type { Metadata } from "next";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SmoothScroll from "./components/SmoothScroll";
import SecurityGuard from "./components/SecurityGuard";
import BanGuard from "./components/BanGuard";
import CreditsExhaustedModal from "./components/CreditsExhaustedModal";

export const metadata: Metadata = {
  title: "KAIZORA",
  description: "Generated by KAIZORA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className="antialiased bg-black text-white"
      >
        <SecurityGuard />
        <BanGuard />
        <CreditsExhaustedModal />
        <SmoothScroll>
          <Navbar />

          <div className="pt-17">{children}</div>

          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
